### ISSUE TITLE
爬100页左右的数据后就被封了

### ISSUE THREAD

**Issue by jiangwei1995910** [chenjiandongx/51job-spider#4]
我改了改你的代码，想多爬点数据，结果大致爬了100页左右以后就被封了。之后就再也获取不到数据了，而且....开代理，改IP都，改浏览器标识都不行，51job反爬虫这么牛逼啊

**Comment by chenjiandongx** [comment]
要不就每次爬取之间延时长一点吧

**Comment by easy16** [comment]
现在运行出错了啦，入口的时候

**Comment by chenjiandongx** [comment]
代码已更新，请安装依赖并运行项目。
